server {
    listen 80;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;

    ssl_certificate     /etc/nginx/ssl/nginx.crt;
    ssl_certificate_key /etc/nginx/ssl/nginx.key;

    resolver 127.0.0.11 valid=10s;
    resolver_timeout 5s;

    location /menu/swagger {
        auth_basic "Developer Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        set $upstream http://product-service:3001;
        rewrite ^/menu/swagger(/.*)?$ /swagger$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /menu {
        set $upstream http://product-service:3001;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /orders/swagger {
        auth_basic "Developer Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        set $upstream http://order-service:3002;
        rewrite ^/orders/swagger(/.*)?$ /swagger$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /orders {
        set $upstream http://order-service:3002;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /kitchen/swagger {
        auth_basic "Developer Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        set $upstream http://kitchen-service:3005;
        rewrite ^/kitchen/swagger(/.*)?$ /swagger$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /kitchen {
        set $upstream http://kitchen-service:3005;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_buffering off;
        proxy_cache off;
        proxy_read_timeout 3600s;
    }

    location /notification/swagger {
        auth_basic "Developer Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        set $upstream http://notification-service:3003;
        rewrite ^/notification/swagger(/.*)?$ /swagger$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /notification {
        set $upstream http://notification-service:3003;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /errors/swagger {
        auth_basic "Developer Access";
        auth_basic_user_file /etc/nginx/.htpasswd;
        set $upstream http://error-service:3004;
        rewrite ^/errors/swagger(/.*)?$ /swagger$1 break;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /errors {
        set $upstream http://error-service:3004;
        proxy_pass $upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

}
